.TH SYSCTL-TIPS 7 "2026年07月" "個人メモ" "ユーザーガイド"
.SH 【名前】
sysctl-tips \- よく使うsysctlコマンドの例集
.SH 【使用例】
.TP
AC動作か、バッテリー動作かを確認する：
.EX
% sysctl hw.acpi.acline
.EE
.TP
バッテリーの残量を確認する：
.EX
% sysctl hw.acpi.battery.life
.EE
.TP
今現在の動作クロックを確認する：
.EX
% sysctl dev.cpu | grep freq:
.EE
.TP
スピーカーのデフォルト出力先を確認する：
.EX
% sysctl hw.snd.default_unit
.EE
.TP
パソコン内部の温度を確認する：
.EX
% sysctl -a | grep temperature
.EE
.TP
接続されているメディアデバイスを確認する：
.EX
% sysctl -n kern.disks
.EE
